# Sentiment Analysis using NLP & Machine Learning

This project builds an end-to-end sentiment analysis system using NLP preprocessing techniques and multiple machine learning models. The goal is to classify text into sentiment categories (Positive/Negative/Neutral) and compare model performance.

In [2]:
# Import libraries

import pandas as pd
import numpy as np
import re
import string

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# ML
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

# Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\Kiran
[nltk_data]     T\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\Kiran
[nltk_data]     T\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [4]:
# LOAD DATASET

df = pd.read_csv("IMDB Dataset.csv")  # change path

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
# DATA UNDERSTANDING

print("Shape:", df.shape)
print("\nClass Distribution:\n", df['sentiment'].value_counts())

df.sample(5)

Shape: (50000, 2)

Class Distribution:
 sentiment
positive    25000
negative    25000
Name: count, dtype: int64

                                                  review sentiment
33677  Killjoy 2 surpasses the first movie by just a ...  negative
45382  As I have said before in previous comments, so...  positive
44897  The true measure of any fictional piece of wor...  positive
18352  The movie is a starter to what really happened...  positive
8019   I think I was recommended this film by the lad...  positive

# NLP PREPROCESSING

In [9]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()  # lowercasing
    
    text = re.sub(r"http\S+|www\S+", "", text)  # remove URLs
    
    text = re.sub(r"[^a-zA-Z\s]", "", text)  # remove punctuation
    
    tokens = text.split()  # tokenization
    
    tokens = [word for word in tokens if word not in stop_words]  # remove stopwords
    
    tokens = [lemmatizer.lemmatize(word) for word in tokens]  # lemmatization
    
    return " ".join(tokens)

In [ ]:
df['clean_text'] = df['review'].apply(preprocess_text)
df[['review', 'clean_text']].head()

# FEATURE ENGINEERING

In [ ]:
# Bag of Words

bow = CountVectorizer(max_features=5000)

X_bow = bow.fit_transform(df['clean_text'])